name: "Nitro Schema Publish"
description: "Publishes GraphQL schemas to the Nitro registry"
author: "ChilliCream"
branding:
  icon: "upload-cloud"
  color: "purple"

inputs:
  tag:
    description: "The tag of the schema version"
    required: true
  stage:
    description: "The name of the stage"
    required: true
  api-id:
    description: "The ID of the API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  force:
    description: "Will not ask for confirmation on deletes or overwrites"
    required: false
    default: "false"
  wait-for-approval:
    description: "Wait for approval"
    required: false
    default: "false"
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false
  job-id:
    description: "The ID of the current job"
    required: false
    default: ${{ job.check_run_id }}

runs:
  using: "node20"
  main: "dist/index.js"
